// src/lib/mockDataStore.js
// ═══════════════════════════════════════════════════════════════════════════
//  GENERADO AUTOMÁTICAMENTE por scripts/generateMockData.js
//  Fuente: data/CODIGOS CNC.xlsx (inventario real IACYM CNC)
//  No editar a mano — para regenerar: node scripts/generateMockData.js
// ═══════════════════════════════════════════════════════════════════════════

function daysFromNow(days) {
    const d = new Date();
    d.setDate(d.getDate() + days);
    return { toDate: () => d, seconds: d.getTime() / 1000 };
}

function daysAgo(days) {
    const d = new Date();
    d.setDate(d.getDate() - days);
    return { toDate: () => d, seconds: d.getTime() / 1000 };
}

// ─── CATEGORÍAS ──
export const MOCK_CATEGORIAS = [
    {
        id: "cat_instrumentos_musicales",
        nombre: "Instrumentos Musicales",
        descripcion: "Categoría de Instrumentos Musicales",
        color: "#8B5CF6",
        icono: "🎵",
        orden: 1,
        activa: true
    },
    {
        id: "cat_mobiliario",
        nombre: "Mobiliario",
        descripcion: "Categoría de Mobiliario",
        color: "#3B82F6",
        icono: "🪑",
        orden: 2,
        activa: true
    },
    {
        id: "cat_tecnologia",
        nombre: "Tecnología",
        descripcion: "Categoría de Tecnología",
        color: "#10B981",
        icono: "💻",
        orden: 3,
        activa: true
    },
    {
        id: "cat_equipos",
        nombre: "Equipos",
        descripcion: "Categoría de Equipos",
        color: "#F59E0B",
        icono: "⚙️",
        orden: 4,
        activa: true
    },
    {
        id: "cat_iluminacion",
        nombre: "Iluminación",
        descripcion: "Categoría de Iluminación",
        color: "#EAB308",
        icono: "💡",
        orden: 5,
        activa: true
    },
    {
        id: "cat_accesorios",
        nombre: "Accesorios",
        descripcion: "Categoría de Accesorios",
        color: "#6366F1",
        icono: "🔧",
        orden: 6,
        activa: true
    },
    {
        id: "cat_accesorios_de_pintura",
        nombre: "Accesorios de Pintura",
        descripcion: "Categoría de Accesorios de Pintura",
        color: "#EC4899",
        icono: "🎨",
        orden: 7,
        activa: true
    },
    {
        id: "cat_herramientas",
        nombre: "Herramientas",
        descripcion: "Categoría de Herramientas",
        color: "#F97316",
        icono: "🔨",
        orden: 8,
        activa: true
    },
    {
        id: "cat_herramientas_de_pintura",
        nombre: "Herramientas de Pintura",
        descripcion: "Categoría de Herramientas de Pintura",
        color: "#D946EF",
        icono: "🖌️",
        orden: 9,
        activa: true
    },
    {
        id: "cat_limpieza",
        nombre: "Limpieza",
        descripcion: "Categoría de Limpieza",
        color: "#14B8A6",
        icono: "🧹",
        orden: 10,
        activa: true
    },
    {
        id: "cat_decoracion",
        nombre: "Decoración",
        descripcion: "Categoría de Decoración",
        color: "#EF4444",
        icono: "🎉",
        orden: 12,
        activa: true
    },
    {
        id: "cat_seguridad",
        nombre: "Seguridad",
        descripcion: "Categoría de Seguridad",
        color: "#DC2626",
        icono: "🔒",
        orden: 13,
        activa: true
    }
].map((c, i) => ({ ...c, fecha_creacion: daysAgo(90 - i) }));

// ─── PRODUCTOS (inventario real de la iglesia) ──
export const MOCK_PRODUCTOS = [
    {
        id: "p1",
        nombre: "BATERIA ELECTRONICA",
        descripcion: "ROLAND TD07",
        categoria: "Instrumentos Musicales",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Ministerio de Adoración",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "INSTB1"
    },
    {
        id: "p2",
        nombre: "GUITARRA",
        descripcion: "MARRON",
        categoria: "Instrumentos Musicales",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Ministerio de Adoración",
        observaciones: "ES PRESTADO",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "INSTG1"
    },
    {
        id: "p3",
        nombre: "PIANO GRANDE",
        descripcion: "MARCA YAMAHA",
        categoria: "Instrumentos Musicales",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Ministerio de Adoración",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "INSTP1"
    },
    {
        id: "p4",
        nombre: "ESCALERAS DE CORO",
        descripcion: "2 PISOS DE COLOR NEGRO",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOBIL1"
    },
    {
        id: "p5",
        nombre: "PANTALLA LED GRANDE",
        descripcion: "4 X2 DE METRAJE",
        categoria: "Tecnología",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "TECNPG1"
    },
    {
        id: "p6",
        nombre: "MESA DE VIDIRIO",
        descripcion: "PARA USO DE PREDICA",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOBMV1"
    },
    {
        id: "p7",
        nombre: "CONSOLAS",
        descripcion: "BEHRINGER RACK",
        categoria: "Equipos",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "EPCON1"
    },
    {
        id: "p8",
        nombre: "FRESNELES",
        descripcion: "ILUMINACION FRONTAL 800WTS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 4,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUFRE1"
    },
    {
        id: "p9",
        nombre: "COBS",
        descripcion: "ILUMINACION FRONTAL 400 WTS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 6,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUCOB2"
    },
    {
        id: "p10",
        nombre: "BEANS",
        descripcion: "ILUMINACION MOVIL 500 WTS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUBEA3"
    },
    {
        id: "p11",
        nombre: "SPOTS",
        descripcion: "ILUMINACION MOVIL 100 WTS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUSPO4"
    },
    {
        id: "p12",
        nombre: "BRUTS",
        descripcion: "ILUMINACION DE AMBIENTE 500 WTS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUBRU5"
    },
    {
        id: "p13",
        nombre: "PARLED",
        descripcion: "ILUMINACION AMBIENTE 100 WTS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 6,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUPAR6"
    },
    {
        id: "p14",
        nombre: "MINI PARLED",
        descripcion: "ILUMINACION DE AMBIENTE 50 WTS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 6,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUMIN7"
    },
    {
        id: "p15",
        nombre: "WASH",
        descripcion: "ILUMINACION MOVIL 700 WTS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUWAS8"
    },
    {
        id: "p16",
        nombre: "MAQUINA DE HUMO",
        descripcion: "COLOR GRIS",
        categoria: "Iluminación",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LUMAQ9"
    },
    {
        id: "p17",
        nombre: "PARLANTES",
        descripcion: "MARCA BAT BLACK",
        categoria: "Equipos",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "EQBAT2"
    },
    {
        id: "p18",
        nombre: "PIANO MEDIANO",
        descripcion: "CROME",
        categoria: "Instrumentos Musicales",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "INSTPI2"
    },
    {
        id: "p19",
        nombre: "COMPUTADORA",
        descripcion: "CPU, PANTALLA , MOUSE , TECLADO",
        categoria: "Tecnología",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "TECOM1"
    },
    {
        id: "p20",
        nombre: "PARANTES DE MICROFONO",
        descripcion: "COLOR NEGRO",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 5,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACCPA1"
    },
    {
        id: "p21",
        nombre: "CABLES DE LUCES",
        descripcion: "COLOR NEGRO LARGOS",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 35,
        stock_minimo: 7,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SU BUSQUEDA SERA POR ITEM",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "COCAB1"
    },
    {
        id: "p22",
        nombre: "CABLES DE AUDIO",
        descripcion: "COLOR NEGRO LARGO",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 30,
        stock_minimo: 6,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SU BUSQUEDA SERA POR ITEM",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "COCAB2"
    },
    {
        id: "p23",
        nombre: "CABLES DE PODER DE AUDIO",
        descripcion: "COLOR NEGRO LARGOS",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SU BUSQUEDA SERA POR ITEM",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "COCAB3"
    },
    {
        id: "p24",
        nombre: "PARANTES DE INSTRUMENTOS",
        descripcion: "COLOR NEGRO",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "COCAB4"
    },
    {
        id: "p25",
        nombre: "PARANTES DE TECLADO",
        descripcion: "COLOR NEGRO",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACCPA3"
    },
    {
        id: "p26",
        nombre: "MICROFONOS INALAMBRICOS",
        descripcion: "RECEPTOR Y TRANSMISOR",
        categoria: "Equipos",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 4,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "EQMIC6"
    },
    {
        id: "p27",
        nombre: "SWITCH DE RED",
        descripcion: "PARA AUDIO",
        categoria: "Equipos",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "EQSWI7"
    },
    {
        id: "p28",
        nombre: "SNAKE DIGITAL",
        descripcion: "PARA AUDIO",
        categoria: "Equipos",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "EQSNA8"
    },
    {
        id: "p29",
        nombre: "ESTABILIZADOR DE CORRIENTE",
        descripcion: "1000 WTS FORZA",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "COEST4"
    },
    {
        id: "p30",
        nombre: "ESTACIONES DE CORRIENTE",
        descripcion: "PARA AUDIO",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 5,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "COEST5"
    },
    {
        id: "p31",
        nombre: "ADORNO FLORAL",
        descripcion: "COLOR MELON ARTIFICIAL",
        categoria: "Decoración",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "DEADOR1"
    },
    {
        id: "p32",
        nombre: "SILLAS PLOMAS",
        descripcion: "SILLAS MEDIANAS PARA LOS CULTOS",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 246,
        stock_minimo: 49,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "BUSQUEDA POR ITEM",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOSILL2"
    },
    {
        id: "p33",
        nombre: "MESAS DE FIERRO",
        descripcion: "MESAS CUADRICULADAS",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOMES1"
    },
    {
        id: "p34",
        nombre: "PIZARRA GRANDE",
        descripcion: "PIZARRA BLANCA",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACCPI3"
    },
    {
        id: "p35",
        nombre: "CUADROS DECORATIVOS",
        descripcion: "FONDO MARRON Y BORDES NEGROS",
        categoria: "Decoración",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 10,
        stock_minimo: 2,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "DEADOR2"
    },
    {
        id: "p36",
        nombre: "ESCALERA",
        descripcion: "PLOMA DE TAMAÑO GRANDE",
        categoria: "Limpieza",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LIASP1"
    },
    {
        id: "p37",
        nombre: "ASPIRADORA",
        descripcion: "MARCA KARCHER",
        categoria: "Limpieza",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "LIASP2"
    },
    {
        id: "p38",
        nombre: "MESAS GRANDES",
        descripcion: "COLOR PLOMA RECTANGULAR",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 14,
        stock_minimo: 2,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOIMEG1"
    },
    {
        id: "p39",
        nombre: "MESAS GRANDES",
        descripcion: "COLOR BLANCO REDONDO",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 14,
        stock_minimo: 2,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOMEG2"
    },
    {
        id: "p40",
        nombre: "ALFOMBRAS ROJAS",
        descripcion: "ROLLOS PARA MATRIMONIO",
        categoria: "Decoración",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 4,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE BUSCARÁ POR ITEM",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "DEALF4"
    },
    {
        id: "p41",
        nombre: "PISOS NEGROS",
        descripcion: "PIEZAS",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 14,
        stock_minimo: 2,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE BUSCARÁ POR ITEM",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACPI1"
    },
    {
        id: "p42",
        nombre: "PISO NEGRO",
        descripcion: "LARGO Y PEQUEÑO DE PLASTICO PARA EL POLLO KANGA",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE BUSCARÁ POR ITEM",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACPI2"
    },
    {
        id: "p43",
        nombre: "PISCINA AZUL",
        descripcion: "228 CMX 159 CM",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACCPI1"
    },
    {
        id: "p44",
        nombre: "PISCINA AZUL",
        descripcion: "2.39 X 1.50 M 58 CM",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA COLOCAR STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACCPI2"
    },
    {
        id: "p45",
        nombre: "PISOS TRANSPARENTES",
        descripcion: "2 ROLLOS",
        categoria: "Accesorios",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE BUSCARÁ POR ÍTEM",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACPI3"
    },
    {
        id: "p46",
        nombre: "ESCALERA PEQUEÑA",
        descripcion: "COLOR PLOMO DE 3 PISOS",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOBES2"
    },
    {
        id: "p47",
        nombre: "BIOMBO ROJO",
        descripcion: "CON RUEDAS Y BORDES PLOMAS",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 7,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOBBI1"
    },
    {
        id: "p48",
        nombre: "EXTINTOR",
        descripcion: "USO EN CASO DE INCENDIOS",
        categoria: "Seguridad",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "SEG1"
    },
    {
        id: "p49",
        nombre: "ESTUCHE DE PIANO",
        descripcion: "PIANO GRANDE",
        categoria: "Seguridad",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "DESGASTADO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "ACCPA2"
    },
    {
        id: "p50",
        nombre: "MESA PEQUEÑA",
        descripcion: "CUADRICULAR DE MADERA",
        categoria: "Mobiliario",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "SE COLOCO STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "MOBMP1"
    },
    {
        id: "p51",
        nombre: "PANTALLA MEDIANA",
        descripcion: "",
        categoria: "Tecnología",
        ubicacion: "TEMPLO",
        ubicacion_nombre: "Templo Principal",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Imagen y Producción",
        observaciones: "FALTA COLOCAR STIKER",
        piso: "PRIMER PISO",
        fuente: "TEMPLO",
        codigo_barras: "TECNPM2"
    },
    {
        id: "p52",
        nombre: "BIOMBOS ROJOS",
        descripcion: "SEPARADORES",
        categoria: "Accesorios",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 13,
        stock_minimo: 2,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "MOBBI1"
    },
    {
        id: "p53",
        nombre: "BADILEJOS",
        descripcion: "MANGO DE COLOR ROJO , AMARILLO",
        categoria: "Herramientas de Pintura",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "PIBAD1"
    },
    {
        id: "p54",
        nombre: "COMBAS",
        descripcion: "PARA CONTRUCCION",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HECOM1"
    },
    {
        id: "p55",
        nombre: "WINCHA",
        descripcion: "MARCA TRUPER 8M/26",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HEWIN1"
    },
    {
        id: "p56",
        nombre: "MARTILLO DE CARPINTERIA",
        descripcion: "MANGA MARRON",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HEMAR1"
    },
    {
        id: "p57",
        nombre: "MARTILLO DE GOMA",
        descripcion: "COLOR BLANCO",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERMAR2"
    },
    {
        id: "p58",
        nombre: "JALADORES DE AGUA",
        descripcion: "TURQUEZA Y COLOR NEGRO",
        categoria: "Limpieza",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "LIMJAL1"
    },
    {
        id: "p59",
        nombre: "LAMELUNA",
        descripcion: "COLOR NEGRO DE TAMAÑO PEQUEÑO",
        categoria: "Limpieza",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "LIMLUN1"
    },
    {
        id: "p60",
        nombre: "LLANAS",
        descripcion: "NORMAL Y ADIENTADA",
        categoria: "Accesorios de Pintura",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ACCLLA1"
    },
    {
        id: "p61",
        nombre: "ARCO DE CIERRA",
        descripcion: "COLOR AMARILLO CON MANGO NEGRO",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERARC1"
    },
    {
        id: "p62",
        nombre: "EXTENSIONES",
        descripcion: "COLOR PLOMO Y NEGRO",
        categoria: "Accesorios",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 6,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "CONEXT1"
    },
    {
        id: "p63",
        nombre: "LLAVE RATCHE T",
        descripcion: "COLOR PLOMO",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERLLA1"
    },
    {
        id: "p64",
        nombre: "CUCHILLAS",
        descripcion: "COLOR PLOMO CON NAVAJA",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERCUC1"
    },
    {
        id: "p65",
        nombre: "TIJERA",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERTI1"
    },
    {
        id: "p66",
        nombre: "TIJERA DE MAYOLICA",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERTI2"
    },
    {
        id: "p67",
        nombre: "PISTOLA DE GRAPAS",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERPI11"
    },
    {
        id: "p68",
        nombre: "RODILLERAS",
        descripcion: "",
        categoria: "Seguridad",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "SEGRO1"
    },
    {
        id: "p69",
        nombre: "RASPADOR DE DRYWALL",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERRAS1"
    },
    {
        id: "p70",
        nombre: "LINTERNAS",
        descripcion: "",
        categoria: "Iluminación",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "LULINT1"
    },
    {
        id: "p71",
        nombre: "KIT DE INSTALACION PISO LAMINADO",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERKIT1"
    },
    {
        id: "p72",
        nombre: "LLAVE TIPO T",
        descripcion: "NUMERO 11",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERLLA1"
    },
    {
        id: "p73",
        nombre: "CIERRA",
        descripcion: "PARA DRYWALL",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERCIE1"
    },
    {
        id: "p74",
        nombre: "DESTAPADOR DE BALDES",
        descripcion: "DE PINTURA COLOR AMARILLO",
        categoria: "Accesorios de Pintura",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ACCDES1"
    },
    {
        id: "p75",
        nombre: "NIVEL DE ALUMINIO",
        descripcion: "PEQUEÑO PLOMO Y GRANDE AMARILLO",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERNI1"
    },
    {
        id: "p76",
        nombre: "TIJERA PARA DRYWALL",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERTI3"
    },
    {
        id: "p77",
        nombre: "PINZADE DRYWALL",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERPIN1"
    },
    {
        id: "p78",
        nombre: "ALICATE PELADOR DE CABLE",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERAL1"
    },
    {
        id: "p79",
        nombre: "ALICATE PARA CABLE INTERNET",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERAL2"
    },
    {
        id: "p80",
        nombre: "ALICATE SIMPLE",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERAL 3"
    },
    {
        id: "p81",
        nombre: "ALICATE PUNTA",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERAL 4"
    },
    {
        id: "p82",
        nombre: "REGLA DE ANGULO",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERRE1"
    },
    {
        id: "p83",
        nombre: "PRENSA ESQUINERA",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HEPREN1"
    },
    {
        id: "p84",
        nombre: "CEPILLO METALICO",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERCE1"
    },
    {
        id: "p85",
        nombre: "LLAVE ALLEN",
        descripcion: "COLOR AZUL",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERLLA1"
    },
    {
        id: "p86",
        nombre: "RASPADOR DE PISO",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERRAS2"
    },
    {
        id: "p87",
        nombre: "SET DE BROCAS",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERSET1"
    },
    {
        id: "p88",
        nombre: "ACCESORIO DESTORNILLADOR",
        descripcion: "COLOCADO EN SET",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERDE1"
    },
    {
        id: "p89",
        nombre: "ACCESORIO DADOS DESTORNILLADOR",
        descripcion: "",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERDD2"
    },
    {
        id: "p90",
        nombre: "ACCESORIO DESTORNILLADOR CEPILLO",
        descripcion: "PLASTICO",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERDE2"
    },
    {
        id: "p91",
        nombre: "LLAVE ESTILSO",
        descripcion: "MANGO NARANJA 1O PULGADAS",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERLLA3"
    },
    {
        id: "p92",
        nombre: "LLAVE FRANCESA",
        descripcion: "10 PULGADAS",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERLLA4"
    },
    {
        id: "p93",
        nombre: "BROCA PARA BIZARRA",
        descripcion: "MELAMINA",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERBR1"
    },
    {
        id: "p94",
        nombre: "DESARMADORES",
        descripcion: "PUNTA PLANA Y PUNTA ESTRELLA",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 6,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERDES1"
    },
    {
        id: "p95",
        nombre: "LUZ DE AUDITORIO",
        descripcion: "NICE WAY",
        categoria: "Iluminación",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "LUZA1"
    },
    {
        id: "p96",
        nombre: "LUZ DE EMERGENCIA",
        descripcion: "WAYLEEE",
        categoria: "Iluminación",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "LUEME1"
    },
    {
        id: "p97",
        nombre: "LUZ HIBAY",
        descripcion: "PORTIZA",
        categoria: "Iluminación",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 7,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "LUHIB1"
    },
    {
        id: "p98",
        nombre: "LUZ SPOT",
        descripcion: "12 WTS",
        categoria: "Iluminación",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 7,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "LUSPO1"
    },
    {
        id: "p99",
        nombre: "FOCO LED",
        descripcion: "TRACK LIGHT DAXSO 20 W",
        categoria: "Iluminación",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 5,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "LO QUE HAY EN EL TEMPLO",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "LUFOC1"
    },
    {
        id: "p100",
        nombre: "REPETIDORES DE WIFI",
        descripcion: "MARCA HUAWI",
        categoria: "Accesorios",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "REWI1"
    },
    {
        id: "p101",
        nombre: "TOMA CORRIENTES",
        descripcion: "",
        categoria: "Accesorios",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 3,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ACCCO1"
    },
    {
        id: "p102",
        nombre: "LIGADORA EECTRICA",
        descripcion: "INGCO",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERLIG"
    },
    {
        id: "p103",
        nombre: "CARGADORES DE BATERIAS INALAMBBRICAS",
        descripcion: "MARCA DEWALT",
        categoria: "Accesorios",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ACCAR1"
    },
    {
        id: "p104",
        nombre: "CARGADOR INALAMBRICO JOVANT",
        descripcion: "MARCA JOVANT",
        categoria: "Accesorios",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ACCAR2"
    },
    {
        id: "p105",
        nombre: "BATERIA INALAMRICA",
        descripcion: "DEWALT DE 6 AH",
        categoria: "Accesorios",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ACCBA1"
    },
    {
        id: "p106",
        nombre: "BATERIAS JOVANT",
        descripcion: "POTENCIA 2AH",
        categoria: "Accesorios",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ACCBA5"
    },
    {
        id: "p107",
        nombre: "SOPLADOR",
        descripcion: "MARCA BALKER",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERSO1"
    },
    {
        id: "p108",
        nombre: "PISTOLA DE PINTURA",
        descripcion: "MARCA EINHELL",
        categoria: "Accesorios de Pintura",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ACCPIN1"
    },
    {
        id: "p109",
        nombre: "BOMBA DE AGUA SUMERGIBLE",
        descripcion: "1 HP MARCA TOTAL",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "HERBO1"
    },
    {
        id: "p110",
        nombre: "MULTI HERRAMIENTA",
        descripcion: "MARCA DEWALT MODELO XR",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "MUH"
    },
    {
        id: "p111",
        nombre: "ATORNOLLADOR DRAWOR",
        descripcion: "MARCA DEWALT MODELO XR",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ATDRAW"
    },
    {
        id: "p112",
        nombre: "AMOLADORA INALAMBRICA",
        descripcion: "MARCA DEWALT MODELO XR",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "AMINALAMBRI"
    },
    {
        id: "p113",
        nombre: "TALADOR PERCUTOR",
        descripcion: "ATORNILLADOR MARCA DEWALT",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "TAPERCUT"
    },
    {
        id: "p114",
        nombre: "TALDRO PERCUTOR",
        descripcion: "ATORNILLADOR MARAC JOVANT COLOR VERDE",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "TA"
    },
    {
        id: "p115",
        nombre: "ATORNILLADOR DE IMPACTO",
        descripcion: "MARCA DEWALT MODELO XR",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "ATIMPAC"
    },
    {
        id: "p116",
        nombre: "KIT CAJA DE HERRAMIENTAS",
        descripcion: "MILWAUKEE , SE GUARDA TORNILLOS GRAPAS",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "KIHERRAMIENT"
    },
    {
        id: "p117",
        nombre: "KIT DE HERRAMIENTAS",
        descripcion: "MARCA DE WALT COLOR NEGRO",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "KI"
    },
    {
        id: "p118",
        nombre: "2 MALETAS DE HERRMAINETAS",
        descripcion: "DE TELA MARCA DEWALT",
        categoria: "Herramientas",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 2,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "2 HERRMAINET"
    },
    {
        id: "p119",
        nombre: "SOMBRILLA COLOR BEIGE",
        descripcion: "3 X3 METROS",
        categoria: "Decoración",
        ubicacion: "ALMACEN_B1",
        ubicacion_nombre: "Almacén B1",
        stock_actual: 1,
        stock_minimo: 1,
        unidad: "pieza",
        estado: "OPTIMO",
        responsabilidad: "Mantenimiento",
        observaciones: "FALTA STIKER",
        piso: "Piso 1",
        fuente: "ALMACENES",
        codigo_barras: "SOBEI"
    }
].map((p, i) => ({ ...p, ultima_actualizacion: daysAgo(i % 30) }));

// ─── CONTEOS DIARIOS ──
export const MOCK_CONTEOS = [];

// ─── MOVIMIENTOS ──
export const MOCK_MOVIMIENTOS = MOCK_PRODUCTOS.filter(p => p.stock_actual > 0).map((p, i) => ({
    id: `m${i + 1}`,
    producto_id: p.id,
    nombre_producto: p.nombre,
    tipo: 'INGRESO',
    cantidad: p.stock_actual,
    usuario: 'Sistema',
    ubicacion: p.ubicacion,
    fecha: daysAgo(90),
    motivo_merma: null,
}));
