'use client';
import { createContext, useContext, useState, useMemo, useCallback } from 'react';

// Diccionario de traducciones (Español, Inglés, Chino, Japonés)
const translations = {
    es: {
        // Generales
        dashboard: 'Dashboard',
        inventario: 'Inventario',
        compras: 'Compras',
        mermas: 'Movimientos de Inventario',
        configuracion: 'Configuración',
        bienvenido: 'Bienvenido',
        movimientos: 'Movimientos',

        // Panel Dashboard
        alertasROP: 'Alertas ROP',
        productosBajoStock: 'Productos bajo stock mínimo',
        mermasMes: 'Mermas del Mes',
        registrosMerma: 'Registros de merma actuales',
        solicitudesPendientes: 'Solicitudes Pendientes',
        esperandoValidacion: 'Esperando validación',
        totalProductos: 'Total Productos',
        enCatalogo: 'En catálogo activo',
        semaforoVencimientos: 'Semáforo de Vencimientos',
        productosProximosVencer: 'Productos próximos a vencer ordenados por urgencia',
        urgente: 'Urgente',
        proximo: 'Próximo',
        ok: 'OK',
        producto: 'Producto',
        vencimiento: 'Vencimiento',
        tipo: 'Tipo',
        alertasCompra: 'Alertas de Compra (ROP)',
        stockActualMenorMInimo: 'Stock actual ≤ stock mínimo de seguridad',
        aReponer: 'a reponer',
        stock: 'Stock',
        min: 'min',

        // Sidebar & Header
        cambiarRol: 'Cambiar Rol',
        rol: 'Rol',
        menu: 'Menú',

        // Inventario
        categoriaTodos: 'Todos',
        buscarProducto: 'Buscar producto...',
        tocaParaActualizar: 'Toca un producto para actualizar el stock',
        cantidad: 'Cantidad',
        guardarStock: 'Guardar Stock',
        registrarMerma: 'Registrar Merma',
        actualizarStock: 'Actualizar Stock',
        motivoMerma: 'Motivo de la merma (ej. vencido, roto)...',
        stockActualizado: 'Stock actualizado',

        // Compras
        sugerenciasROP: 'Sugerencias ROP',
        motorROP: 'Motor ROP – Productos a Comprar Hoy',
        stockComprarAprox: 'Comprar aprox.',
        requerimientos: 'Requerimientos (Firmas)',
        solicitadoPor: 'Solicitado por',
        hace: 'Hace',
        dias: 'días',
        horas: 'horas',
        estado: 'Estado',
        aprobarComoAdmin: 'Aprobar como Admin',
        validarComoGerencia: 'Validar como Gerencia',
        marcarComprado: 'Marcar como Comprado',
        rechazar: 'Rechazar',
        verHistorial: 'Ver Historial',
        historialFirmas: 'Historial de Firmas',
        cerrar: 'Cerrar',

        // Mermas / Movimientos
        mermasEHistorial: 'Movimientos e Historial',
        ingresos: 'Ingresos',
        salidas: 'Salidas',
        historialMovimientos: 'Historial de Movimientos',
        filtroTodos: 'Todos_Movimientos',
        buscar: 'Buscar...',
        fecha: 'Fecha',
        motivo: 'Motivo',
        usuario: 'Usuario',
        merma: 'Merma',
        ingreso: 'Ingreso',
        salida: 'Salida',
        noMovimientos: 'No hay movimientos con los filtros actuales.',

        // Extras & Compartidos
        tipo: 'Tipo',
        registros: 'Registros',
        categoria: 'Categoría',
        alerta: 'Alerta',
        nivel: 'Nivel',
        accion: 'Acción',
        log: 'Log',
        editar: 'Editar',
        sinResultados: 'Sin resultados',
        sinDatos: 'Sin datos',
        todas: 'Todas',
        desayuno: 'Desayuno',
        limpieza: 'Limpieza',
        frigobar: 'Frigobar',
        cocina: 'Cocina',
        ejMotivoMerma: 'Ej: Producto vencido, derrame, contaminación...',
        ajustaFiltros: 'Ajusta los filtros de búsqueda.',
        sinProductosVencer: 'Sin productos próximos a vencer',
        tocaProductoActualizar: 'Toca un producto para actualizar stock',
        productos: 'Productos',
        todosProductosVigentes: 'Todos los productos tienen más de 30 días de vigencia.',
        stockOk: 'Stock OK',
        noAlertasReorden: 'No hay alertas de reorden activas.',
        noSugerenciasROP: 'No hay sugerencias de compra por ROP en este momento.',
        noRequerimientos: 'No hay requerimientos en curso.',
        contrasenaIncorrecta: 'Contraseña incorrecta. Intenta de nuevo.',
        seguridadAcceso: 'Seguridad de Acceso',
        ingresaContrasena: 'Ingresa la contraseña para acceder como',
        acceder: 'Acceder',
        contrasenaPlaceholder: 'Contraseña / PIN',
        guardando: 'Guardando...',
        items: 'Items'
    },
    en: {
        // General
        dashboard: 'Dashboard',
        inventario: 'Inventory',
        compras: 'Purchases',
        mermas: 'Wastage',
        configuracion: 'Settings',
        bienvenido: 'Welcome',
        movimientos: 'Movements',

        // Dashboard Panel
        alertasROP: 'ROP Alerts',
        productosBajoStock: 'Products below minimum stock',
        mermasMes: 'Monthly Wastage',
        registrosMerma: 'Current wastage records',
        solicitudesPendientes: 'Pending Requests',
        esperandoValidacion: 'Waiting for validation',
        totalProductos: 'Total Products',
        enCatalogo: 'In active catalog',
        semaforoVencimientos: 'Expiration Traffic Light',
        productosProximosVencer: 'Products close to expiration sorted by urgency',
        urgente: 'Urgent',
        proximo: 'Soon',
        ok: 'OK',
        producto: 'Product',
        vencimiento: 'Expiration',
        tipo: 'Type',
        alertasCompra: 'Purchase Alerts (ROP)',
        stockActualMenorMInimo: 'Current stock ≤ minimum safety stock',
        aReponer: 'to restock',
        stock: 'Stock',
        min: 'min',

        // Sidebar & Header
        cambiarRol: 'Switch Role',
        rol: 'Role',
        menu: 'Menu',

        // Inventory
        categoriaTodos: 'All',
        buscarProducto: 'Search product...',
        tocaParaActualizar: 'Tap a product to update stock',
        cantidad: 'Quantity',
        guardarStock: 'Save Stock',
        registrarMerma: 'Register Waste',
        actualizarStock: 'Update Stock',
        motivoMerma: 'Reason for waste (e.g., expired, broken)...',
        stockActualizado: 'Stock updated',

        // Purchases
        sugerenciasROP: 'ROP Suggestions',
        motorROP: 'ROP Engine – Products to Buy Today',
        stockComprarAprox: 'Buy approx.',
        requerimientos: 'Requests (Approvals)',
        solicitadoPor: 'Requested by',
        hace: 'Ago',
        dias: 'days',
        horas: 'hours',
        estado: 'Status',
        aprobarComoAdmin: 'Approve (Admin)',
        validarComoGerencia: 'Validate (Management)',
        marcarComprado: 'Mark as Purchased',
        rechazar: 'Reject',
        verHistorial: 'View Logic',
        historialFirmas: 'Approval History',
        cerrar: 'Close',

        // Wastage
        mermasEHistorial: 'Wastage & History',
        ingresos: 'Inbounds',
        salidas: 'Outbounds',
        historialMovimientos: 'Movement History',
        filtroTodos: 'All_Movements',
        buscar: 'Search...',
        fecha: 'Date',
        motivo: 'Reason',
        usuario: 'User',
        merma: 'Wastage',
        ingreso: 'Inbound',
        salida: 'Outbound',
        noMovimientos: 'No movements found with the current filters.',

        // Extras & Shared
        tipo: 'Type',
        registros: 'Records',
        categoria: 'Category',
        alerta: 'Alert',
        nivel: 'Level',
        accion: 'Action',
        log: 'Log',
        editar: 'Edit',
        sinResultados: 'No results',
        sinDatos: 'No data',
        todas: 'All',
        desayuno: 'Breakfast',
        limpieza: 'Cleaning',
        frigobar: 'Minibar',
        cocina: 'Kitchen',
        ejMotivoMerma: 'Ex: Expired product, spill, contamination...',
        ajustaFiltros: 'Adjust your search filters.',
        sinProductosVencer: 'No products expiring soon',
        tocaProductoActualizar: 'Tap a product to update stock',
        productos: 'Products',
        todosProductosVigentes: 'All products are valid for more than 30 days.',
        stockOk: 'Stock OK',
        noAlertasReorden: 'No active reorder alerts.',
        noSugerenciasROP: 'No ROP purchase suggestions at this time.',
        noRequerimientos: 'No pending requests.',
        contrasenaIncorrecta: 'Incorrect password. Try again.',
        seguridadAcceso: 'Access Security',
        ingresaContrasena: 'Enter password to access as',
        acceder: 'Login',
        contrasenaPlaceholder: 'Password / PIN',
        guardando: 'Saving...',
        items: 'Items'
    },
    zh: {
        // General
        dashboard: '仪表板',
        inventario: '库存',
        compras: '采购',
        mermas: '损耗',
        configuracion: '设置',
        bienvenido: '欢迎',
        movimientos: '变动',

        // Dashboard Panel
        alertasROP: 'ROP 警报',
        productosBajoStock: '低于最低库存的产品',
        mermasMes: '本月损耗',
        registrosMerma: '当前损耗记录',
        solicitudesPendientes: '待处理请求',
        esperandoValidacion: '等待验证',
        totalProductos: '总产品',
        enCatalogo: '在活跃目录中',
        semaforoVencimientos: '到期红绿灯',
        productosProximosVencer: '按紧急程度排序的即将到期产品',
        urgente: '紧急',
        proximo: '即将',
        ok: '正常',
        producto: '产品',
        vencimiento: '到期',
        tipo: '类型',
        alertasCompra: '采购警报 (ROP)',
        stockActualMenorMInimo: '当前库存 ≤ 最低安全库存',
        aReponer: '需补充',
        stock: '库存',
        min: '最少',

        // Sidebar & Header
        cambiarRol: '切换角色',
        rol: '角色',
        menu: '菜单',

        // Inventory
        categoriaTodos: '全部',
        buscarProducto: '搜索产品...',
        tocaParaActualizar: '点击产品更新库存',
        cantidad: '数量',
        guardarStock: '保存库存',
        registrarMerma: '记录损耗',
        actualizarStock: '更新库存',
        motivoMerma: '损耗原因 (例如：过期，破损)...',
        stockActualizado: '库存已更新',

        // Purchases
        sugerenciasROP: 'ROP 建议',
        motorROP: 'ROP 引擎 – 今天要买的产品',
        stockComprarAprox: '预计购买',
        requerimientos: '请求 (审批)',
        solicitadoPor: '申请人',
        hace: '前',
        dias: '天',
        horas: '小时',
        estado: '状态',
        aprobarComoAdmin: '批准 (管理员)',
        validarComoGerencia: '验证 (管理层)',
        marcarComprado: '标记为已购买',
        rechazar: '拒绝',
        verHistorial: '查看历史',
        historialFirmas: '审批历史',
        cerrar: '关闭',

        // Wastage
        mermasEHistorial: '损耗与历史',
        ingresos: '入库',
        salidas: '出库',
        historialMovimientos: '变动历史',
        filtroTodos: '所有_变动',
        buscar: '搜索...',
        fecha: '日期',
        motivo: '原因',
        usuario: '用户',
        merma: '损耗',
        ingreso: '入库',
        salida: '出库',
        noMovimientos: '当前过滤器下未找到记录。',

        // Extras & Shared
        tipo: '类型',
        registros: '记录',
        categoria: '类别',
        alerta: '警报',
        nivel: '级别',
        accion: '操作',
        log: '日志',
        editar: '编辑',
        sinResultados: '无结果',
        sinDatos: '无数据',
        todas: '全部',
        desayuno: '早餐',
        limpieza: '清洁',
        frigobar: '迷你吧',
        cocina: '厨房',
        ejMotivoMerma: '例：产品过期、泄漏、污染...',
        ajustaFiltros: '调整搜索过滤器。',
        sinProductosVencer: '没有即将到期的产品',
        tocaProductoActualizar: '点击产品即可更新库存',
        productos: '产品',
        todosProductosVigentes: '所有产品的有效期均超过 30 天。',
        stockOk: '库存正常',
        noAlertasReorden: '没有活跃的重新订购警报。',
        noSugerenciasROP: '目前没有 ROP 购买建议。',
        noRequerimientos: '没有待处理的请求。',
        contrasenaIncorrecta: '密码错误。请重试。',
        seguridadAcceso: '访问安全',
        ingresaContrasena: '输入密码以登录',
        acceder: '登录',
        contrasenaPlaceholder: '密码 / PIN',
        guardando: '保存中...',
        items: '项目'
    },
    ja: {
        // General
        dashboard: 'ダッシュボード',
        inventario: '在庫',
        compras: '購入',
        mermas: '廃棄',
        configuracion: '設定',
        bienvenido: 'ようこそ',
        movimientos: '移動',

        // Dashboard Panel
        alertasROP: 'ROPアラート',
        productosBajoStock: '最小在庫を下回る製品',
        mermasMes: '今月の廃棄',
        registrosMerma: '現在の廃棄記録',
        solicitudesPendientes: '保留中のリクエスト',
        esperandoValidacion: '検証待ち',
        totalProductos: '総製品数',
        enCatalogo: 'アクティブなカタログ内',
        semaforoVencimientos: '有効期限の信号機',
        productosProximosVencer: '緊急度順の有効期限間近の製品',
        urgente: '緊急',
        proximo: '間近',
        ok: '正常',
        producto: '製品',
        vencimiento: '有効期限',
        tipo: '種類',
        alertasCompra: '購入アラート (ROP)',
        stockActualMenorMInimo: '現在の在庫 ≤ 最小安全在庫',
        aReponer: '補充が必要',
        stock: '在庫',
        min: '最小',

        // Sidebar & Header
        cambiarRol: '役割を切り替える',
        rol: '役割',
        menu: 'メニュー',

        // Inventory
        categoriaTodos: 'すべて',
        buscarProducto: '製品を検索...',
        tocaParaActualizar: '製品をタップして在庫を更新',
        cantidad: '数量',
        guardarStock: '在庫を保存',
        registrarMerma: '廃棄を記録',
        actualizarStock: '在庫を更新',
        motivoMerma: '廃棄理由 (例: 期限切れ、破損)...',
        stockActualizado: '在庫が更新されました',

        // Purchases
        sugerenciasROP: 'ROP の提案',
        motorROP: 'ROPエンジン – 今日買う製品',
        stockComprarAprox: 'おおよその購入',
        requerimientos: 'リクエスト (承認)',
        solicitadoPor: '申請者',
        hace: '前',
        dias: '日',
        horas: '時間',
        estado: 'ステータス',
        aprobarComoAdmin: '承認 (管理者)',
        validarComoGerencia: '検証 (経営陣)',
        marcarComprado: '購入済みとしてマーク',
        rechazar: '拒否する',
        verHistorial: '履歴を表示',
        historialFirmas: '承認履歴',
        cerrar: '閉じる',

        // Wastage
        mermasEHistorial: '廃棄と履歴',
        ingresos: '入庫',
        salidas: '出庫',
        historialMovimientos: '移動履歴',
        filtroTodos: '全ての移動',
        buscar: '検索...',
        fecha: '日付',
        motivo: '理由',
        usuario: 'ユーザー',
        merma: '廃棄',
        ingreso: '入庫',
        salida: '出庫',
        noMovimientos: '現在のフィルターでレコードが見つかりません。',

        // Extras & Shared
        tipo: 'タイプ',
        registros: '記録',
        categoria: 'カテゴリー',
        alerta: 'アラート',
        nivel: 'レベル',
        accion: 'アクション',
        log: 'ログ',
        editar: '編集',
        sinResultados: '結果なし',
        sinDatos: 'データなし',
        todas: 'すべて',
        desayuno: '朝食',
        limpieza: 'クリーニング',
        frigobar: 'ミニバー',
        cocina: 'キッチン',
        ejMotivoMerma: '例：期限切れの製品、こぼれ、汚染...',
        ajustaFiltros: '検索フィルターを調整してください。',
        sinProductosVencer: '期限切れ間近の製品はありません',
        tocaProductoActualizar: '製品をタップして在庫を更新',
        productos: '製品',
        todosProductosVigentes: 'すべての製品の有効期限は30日以上あります。',
        stockOk: '在庫OK',
        noAlertasReorden: 'アクティブな再注文アラートはありません。',
        noSugerenciasROP: '現在、ROP の購入に関する提案はありません。',
        noRequerimientos: '保留中のリクエストはありません。',
        contrasenaIncorrecta: 'パスワードが間違っています。もう一度お試しください。',
        seguridadAcceso: 'アクセスセキュリティ',
        ingresaContrasena: 'パスワードを入力してログイン',
        acceder: 'ログイン',
        contrasenaPlaceholder: 'パスワード / PIN',
        guardando: '保存中...',
        items: 'アイテム'
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('es'); // Default Spanish

    // Función de traducción
    const t = useCallback((key) => {
        return translations[language][key] || key;
    }, [language]);

    const value = useMemo(() => ({
        language,
        setLanguage,
        t
    }), [language, t]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
