'use client';
import { createContext, useContext, useState, useMemo, useCallback } from 'react';

// Diccionario de traducciones – Control de Inventario Bar
const translations = {
    es: {
        // Generales
        dashboard: 'Panel de Control',
        inventario: 'Inventario',
        configuracion: 'Configuración',
        bienvenido: 'Bienvenido',
        movimientos: 'Movimientos',

        // Panel Dashboard
        alertasROP: 'Stock Bajo',
        productosBajoStock: 'Productos bajo stock mínimo',
        conteosDiarios: 'Conteos Hoy',
        conteosRealizados: 'Conteos realizados hoy',
        diferenciasDetectadas: 'Diferencias',
        diferenciasDesc: 'Productos con diferencias en conteo',
        totalProductos: 'Total productos',
        enCatalogo: 'SKU activos en inventario',
        semaforoVencimientos: 'Productos próximos a vencer',
        productosProximosVencer: 'Prioridad según proximidad a fecha de vencimiento',
        urgente: 'Crítico',
        proximo: 'Próximo',
        ok: 'Estable',
        producto: 'Producto',
        vencimiento: 'Vencimiento',
        tipo: 'Tipo',
        alertasCompra: 'Stock bajo mínimo',
        stockActualMenorMInimo: 'Productos que necesitan reposición',
        aReponer: 'A reponer',
        stock: 'Stock',
        min: 'Mín',
        lote: 'Lote',

        // Sidebar & Header
        cambiarRol: 'Cambiar rol',
        rol: 'Rol',
        menu: 'Navegación',

        // Inventario
        categoriaTodos: 'Todas las categorías',
        buscarProducto: 'Buscar producto, código de barras o lote',
        tocaParaActualizar: 'Selecciona un producto para actualizar stock',
        cantidad: 'Cantidad',
        cantidadIngresar: 'Cantidad a ingresar',
        cantidadBaja: 'Cantidad a dar de baja',
        guardarStock: 'Guardar stock',
        actualizarStock: 'Actualizar stock',
        stockActualizado: 'Stock actualizado correctamente',
        stockActual: 'Stock actual',
        minDef: 'Mínimo definido',

        // Conteo
        nuevoConteo: 'Nuevo conteo',
        conteoInventario: 'Conteo de inventario',
        iniciarConteo: 'Iniciar conteo',
        conteoEnProgreso: 'Conteo en progreso',
        conteoCompletado: 'Conteo completado',
        escanearCodigo: 'Escanear código',
        codigoBarras: 'Código de barras',
        conteoFisico: 'Conteo físico',
        stockSistema: 'Stock sistema',
        diferencia: 'Diferencia',
        guardarConteo: 'Guardar conteo',
        finalizarConteo: 'Finalizar conteo',
        productoEscaneado: 'Producto identificado',
        productoNoEncontrado: 'No se encontró producto con ese código',
        ingresaCantidad: 'Ingresa la cantidad contada',
        escanearOtro: 'Escanear otro',
        buscarManual: 'Buscar manual',
        camaraNoDisponible: 'Cámara no disponible',
        permisosCamara: 'Permite el acceso a la cámara para escanear',
        reporteConteo: 'Reporte de conteo',
        sinDiferencias: 'Sin diferencias',
        conDiferencias: 'Con diferencias',
        ajustarStock: 'Ajustar stock',
        confirmarAjuste: '¿Ajustar stock según el conteo físico?',
        ajusteRealizado: 'Ajuste realizado correctamente',
        historialConteos: 'Historial de conteos',
        noConteos: 'No hay conteos registrados',
        detalleConteo: 'Detalle del conteo',
        itemsContados: 'Ítems contados',

        // Movimientos
        fecha: 'Fecha',
        motivo: 'Motivo',
        usuario: 'Usuario',
        ingreso: 'Entrada',
        salida: 'Salida',
        conteo: 'Conteo',

        // Extras & Compartidos
        registros: 'Registros',
        categoria: 'Categoría',
        alerta: 'Alerta',
        nivel: 'Nivel',
        accion: 'Acción',
        editar: 'Editar',
        sinResultados: 'Sin resultados',
        sinDatos: 'Sin datos',
        todas: 'Todas',
        // Categorías del bar
        licores: 'Licores',
        cervezas: 'Cervezas',
        vinos: 'Vinos',
        'bebidas sin alcohol': 'Bebidas sin alcohol',
        'insumos bar': 'Insumos Bar',
        snacks: 'Snacks',
        ajustaFiltros: 'Ajusta los filtros de búsqueda para ver resultados.',
        sinProductosVencer: 'No hay productos próximos a vencer',
        tocaProductoActualizar: 'Selecciona un producto para actualizar stock',
        productos: 'Productos',
        todosProductosVigentes: 'Todos los productos tienen fecha de vencimiento mayor a 30 días.',
        stockOk: 'Stock saludable',
        noAlertasReorden: 'Sin alertas de stock bajo.',
        contrasenaIncorrecta: 'Contraseña incorrecta, inténtalo nuevamente.',
        seguridadAcceso: 'Control de acceso',
        ingresaContrasena: 'Ingresa la contraseña para continuar como',
        acceder: 'Acceder',
        contrasenaPlaceholder: 'Contraseña o PIN',
        guardando: 'Guardando...',
        items: 'Ítems',
        // CRUD Productos
        nuevoProducto: 'Nuevo producto',
        nuevoProductoDesc: 'Completa los datos para registrar un nuevo producto',
        editarProducto: 'Editar producto',
        editarProductoDesc: 'Modifica los datos del producto seleccionado',
        eliminarProducto: 'Eliminar producto',
        confirmarEliminar: '¿Estás seguro de que deseas eliminar este producto? Esta acción no se puede deshacer.',
        eliminar: 'Eliminar',
        crearProducto: 'Crear producto',
        guardarCambios: 'Guardar cambios',
        cancelar: 'Cancelar',
        campoObligatorio: 'El nombre del producto es obligatorio',
        seleccionaCategoria: 'Selecciona una categoría',
        unidad: 'Unidad',
        proveedor: 'Proveedor',
        descripcionProducto: 'Descripción',
        descripcionPlaceholder: 'Descripción breve del producto o notas adicionales',
        // Gestión de categorías
        gestionCategorias: 'Categorías',
        gestionCategoriasDesc: 'Administra las categorías de productos',
        nuevaCategoria: 'Nueva categoría',
        nombreCategoria: 'Nombre de la categoría',
        descripcionCategoria: 'Descripción (opcional)',
        agregarCategoria: 'Agregar categoría',
        sinCategorias: 'No hay categorías registradas',
        cerrar: 'Cerrar',
        marca: 'Marca',
        gramaje: 'Contenido / Gramaje',
        tocaParaContar: 'Toca un producto para contar',
        contando: 'Contando',
        tapsConteo: 'Toca para contar',
        confirmarConteo: 'Confirmar',
        descartarConteo: 'Descartar',
        notas: 'Notas',
        notasConteo: 'Observaciones del conteo',
        resumenDelDia: 'Resumen del día — control de tu inventario',
        verCatalogo: 'Ver catálogo',
        escaneoRapido: 'Identificar producto',
        progresoConteo: 'Progreso del conteo',
    },
    en: {
        dashboard: 'Dashboard',
        inventario: 'Inventory',
        configuracion: 'Settings',
        bienvenido: 'Welcome',
        movimientos: 'Movements',
        alertasROP: 'Low Stock',
        productosBajoStock: 'Products below minimum stock',
        conteosDiarios: 'Counts Today',
        conteosRealizados: 'Counts performed today',
        diferenciasDetectadas: 'Discrepancies',
        diferenciasDesc: 'Products with count discrepancies',
        totalProductos: 'Total products',
        enCatalogo: 'Active SKUs in inventory',
        semaforoVencimientos: 'Products expiring soon',
        productosProximosVencer: 'Prioritized by expiration date',
        urgente: 'Critical',
        proximo: 'Upcoming',
        ok: 'Stable',
        producto: 'Product',
        vencimiento: 'Expiration',
        tipo: 'Type',
        alertasCompra: 'Below minimum stock',
        stockActualMenorMInimo: 'Products that need replenishment',
        aReponer: 'To replenish',
        stock: 'Stock',
        min: 'Min',
        lote: 'Batch',
        cambiarRol: 'Switch role',
        rol: 'Role',
        menu: 'Navigation',
        categoriaTodos: 'All categories',
        buscarProducto: 'Search product, barcode or batch',
        tocaParaActualizar: 'Select a product to update stock',
        cantidad: 'Quantity',
        cantidadIngresar: 'Quantity to receive',
        cantidadBaja: 'Quantity to write off',
        guardarStock: 'Save stock',
        actualizarStock: 'Update stock',
        stockActualizado: 'Stock successfully updated',
        stockActual: 'Current stock',
        minDef: 'Defined minimum',
        nuevoConteo: 'New count',
        conteoInventario: 'Inventory count',
        iniciarConteo: 'Start count',
        conteoEnProgreso: 'Count in progress',
        conteoCompletado: 'Count completed',
        escanearCodigo: 'Scan code',
        codigoBarras: 'Barcode',
        conteoFisico: 'Physical count',
        stockSistema: 'System stock',
        diferencia: 'Difference',
        guardarConteo: 'Save count',
        finalizarConteo: 'Finalize count',
        productoEscaneado: 'Product identified',
        productoNoEncontrado: 'No product found with that code',
        ingresaCantidad: 'Enter the counted quantity',
        escanearOtro: 'Scan another',
        buscarManual: 'Search manually',
        camaraNoDisponible: 'Camera not available',
        permisosCamara: 'Allow camera access to scan',
        reporteConteo: 'Count report',
        sinDiferencias: 'No discrepancies',
        conDiferencias: 'With discrepancies',
        ajustarStock: 'Adjust stock',
        confirmarAjuste: 'Adjust stock according to physical count?',
        ajusteRealizado: 'Adjustment completed successfully',
        historialConteos: 'Count history',
        noConteos: 'No counts registered',
        detalleConteo: 'Count detail',
        itemsContados: 'Items counted',
        fecha: 'Date',
        motivo: 'Reason',
        usuario: 'User',
        ingreso: 'Inbound',
        salida: 'Outbound',
        conteo: 'Count',
        registros: 'Records',
        categoria: 'Category',
        alerta: 'Alert',
        nivel: 'Level',
        accion: 'Action',
        editar: 'Edit',
        sinResultados: 'No results',
        sinDatos: 'No data',
        todas: 'All',
        licores: 'Spirits',
        cervezas: 'Beers',
        vinos: 'Wines',
        'bebidas sin alcohol': 'Soft drinks',
        'insumos bar': 'Bar supplies',
        snacks: 'Snacks',
        ajustaFiltros: 'Refine your filters to discover records.',
        sinProductosVencer: 'Nothing is close to expiring',
        tocaProductoActualizar: 'Select a product to update stock',
        productos: 'Products',
        todosProductosVigentes: 'All products have 30+ days before expiration.',
        stockOk: 'Healthy stock',
        noAlertasReorden: 'No low stock alerts.',
        contrasenaIncorrecta: 'Incorrect password. Please try again.',
        seguridadAcceso: 'Access control',
        ingresaContrasena: 'Enter the password to continue as',
        acceder: 'Sign in',
        contrasenaPlaceholder: 'Password or PIN',
        guardando: 'Saving...',
        items: 'Items',
        nuevoProducto: 'New product',
        nuevoProductoDesc: 'Fill in the details to register a new product',
        editarProducto: 'Edit product',
        editarProductoDesc: 'Update the selected product information',
        eliminarProducto: 'Delete product',
        confirmarEliminar: 'Are you sure you want to delete this product? This action cannot be undone.',
        eliminar: 'Delete',
        crearProducto: 'Create product',
        guardarCambios: 'Save changes',
        cancelar: 'Cancel',
        campoObligatorio: 'Product name is required',
        seleccionaCategoria: 'Select a category',
        unidad: 'Unit',
        proveedor: 'Supplier',
        descripcionProducto: 'Description',
        descripcionPlaceholder: 'Brief product description or additional notes',
        gestionCategorias: 'Categories',
        gestionCategoriasDesc: 'Manage product categories',
        nuevaCategoria: 'New category',
        nombreCategoria: 'Category name',
        descripcionCategoria: 'Description (optional)',
        agregarCategoria: 'Add category',
        sinCategorias: 'No categories registered',
        cerrar: 'Close',
        marca: 'Brand',
        gramaje: 'Content / Weight',
        tocaParaContar: 'Tap a product to count',
        contando: 'Counting',
        tapsConteo: 'Tap to count',
        confirmarConteo: 'Confirm',
        descartarConteo: 'Discard',
        notas: 'Notes',
        notasConteo: 'Count observations',
        resumenDelDia: 'Daily summary — manage your inventory',
        verCatalogo: 'View catalog',
        escaneoRapido: 'Identify product',
        progresoConteo: 'Count progress',
    },
    zh: {
        dashboard: '控制面板',
        inventario: '库存',
        configuracion: '设置',
        bienvenido: '欢迎',
        movimientos: '变动',
        alertasROP: '库存不足',
        productosBajoStock: '低于最低库存的产品',
        conteosDiarios: '今日盘点',
        conteosRealizados: '今日盘点次数',
        diferenciasDetectadas: '差异',
        diferenciasDesc: '盘点有差异的产品',
        totalProductos: '产品总数',
        enCatalogo: '库存活跃SKU',
        semaforoVencimientos: '即将到期产品',
        productosProximosVencer: '按到期时间排序',
        urgente: '紧急',
        proximo: '即将',
        ok: '正常',
        producto: '产品',
        vencimiento: '到期',
        tipo: '类型',
        alertasCompra: '低于最低库存',
        stockActualMenorMInimo: '需要补充的产品',
        aReponer: '需补充',
        stock: '库存',
        min: '最小',
        lote: '批次',
        cambiarRol: '切换角色',
        rol: '角色',
        menu: '菜单',
        categoriaTodos: '全部',
        buscarProducto: '搜索产品/条形码...',
        tocaParaActualizar: '点击产品更新库存',
        cantidad: '数量',
        cantidadIngresar: '入库数量',
        cantidadBaja: '出库数量',
        guardarStock: '保存',
        actualizarStock: '更新库存',
        stockActualizado: '库存已更新',
        stockActual: '当前库存',
        minDef: '最低值',
        nuevoConteo: '新盘点',
        conteoInventario: '库存盘点',
        iniciarConteo: '开始盘点',
        conteoEnProgreso: '盘点中',
        conteoCompletado: '盘点完成',
        escanearCodigo: '扫描条码',
        codigoBarras: '条形码',
        conteoFisico: '实际数量',
        stockSistema: '系统库存',
        diferencia: '差异',
        guardarConteo: '保存盘点',
        finalizarConteo: '完成盘点',
        productoEscaneado: '产品已识别',
        productoNoEncontrado: '未找到该条码的产品',
        ingresaCantidad: '输入盘点数量',
        escanearOtro: '扫描下一个',
        buscarManual: '手动搜索',
        camaraNoDisponible: '相机不可用',
        permisosCamara: '允许相机访问以扫描',
        reporteConteo: '盘点报告',
        sinDiferencias: '无差异',
        conDiferencias: '有差异',
        ajustarStock: '调整库存',
        confirmarAjuste: '根据实际盘点调整库存？',
        ajusteRealizado: '调整成功',
        historialConteos: '盘点历史',
        noConteos: '无盘点记录',
        detalleConteo: '盘点详情',
        itemsContados: '已盘点项目',
        fecha: '日期',
        motivo: '原因',
        usuario: '用户',
        ingreso: '入库',
        salida: '出库',
        conteo: '盘点',
        registros: '记录',
        categoria: '类别',
        alerta: '警报',
        nivel: '级别',
        accion: '操作',
        editar: '编辑',
        sinResultados: '无结果',
        sinDatos: '无数据',
        todas: '全部',
        licores: '烈酒',
        cervezas: '啤酒',
        vinos: '葡萄酒',
        'bebidas sin alcohol': '无酒精饮料',
        'insumos bar': '吧台用品',
        snacks: '零食',
        ajustaFiltros: '调整筛选条件。',
        sinProductosVencer: '没有即将到期的产品',
        tocaProductoActualizar: '点击产品更新库存',
        productos: '产品',
        todosProductosVigentes: '所有产品到期时间超过30天。',
        stockOk: '库存正常',
        noAlertasReorden: '无库存不足警报。',
        contrasenaIncorrecta: '密码错误，请重试。',
        seguridadAcceso: '访问控制',
        ingresaContrasena: '输入密码以',
        acceder: '登录',
        contrasenaPlaceholder: '密码 / PIN',
        guardando: '保存中...',
        items: '项目',
        nuevoProducto: '新产品',
        nuevoProductoDesc: '填写信息以注册新产品',
        editarProducto: '编辑产品',
        editarProductoDesc: '修改所选产品的信息',
        eliminarProducto: '删除产品',
        confirmarEliminar: '确定要删除此产品吗？此操作无法撤消。',
        eliminar: '删除',
        crearProducto: '创建产品',
        guardarCambios: '保存更改',
        cancelar: '取消',
        campoObligatorio: '产品名称为必填项',
        seleccionaCategoria: '请选择一个类别',
        unidad: '单位',
        proveedor: '供应商',
        descripcionProducto: '描述',
        descripcionPlaceholder: '产品简要描述或附加说明',
        gestionCategorias: '类别管理',
        gestionCategoriasDesc: '管理产品类别',
        nuevaCategoria: '新类别',
        nombreCategoria: '类别名称',
        descripcionCategoria: '描述（可选）',
        agregarCategoria: '添加类别',
        sinCategorias: '没有注册的类别',
        cerrar: '关闭',
        marca: '品牌',
        gramaje: '含量 / 重量',
        tocaParaContar: '点击产品开始盘点',
        contando: '盘点中',
        tapsConteo: '点击计数',
        confirmarConteo: '确认',
        descartarConteo: '放弃',
        notas: '备注',
        notasConteo: '盘点备注',
        resumenDelDia: '每日摘要 — 管理您的库存',
        verCatalogo: '查看目录',
        escaneoRapido: '识别产品',
        progresoConteo: '盘点进度',
    },
    ja: {
        dashboard: 'ダッシュボード',
        inventario: '在庫',
        configuracion: '設定',
        bienvenido: 'ようこそ',
        movimientos: '移動',
        alertasROP: '在庫不足',
        productosBajoStock: '最低在庫を下回る製品',
        conteosDiarios: '本日の棚卸',
        conteosRealizados: '本日の棚卸回数',
        diferenciasDetectadas: '差異',
        diferenciasDesc: '棚卸で差異のある製品',
        totalProductos: '製品総数',
        enCatalogo: 'アクティブSKU',
        semaforoVencimientos: '有効期限間近の製品',
        productosProximosVencer: '有効期限順',
        urgente: '緊急',
        proximo: '間近',
        ok: '正常',
        producto: '製品',
        vencimiento: '有効期限',
        tipo: 'タイプ',
        alertasCompra: '最低在庫以下',
        stockActualMenorMInimo: '補充が必要な製品',
        aReponer: '補充必要',
        stock: '在庫',
        min: '最小',
        lote: 'ロット',
        cambiarRol: '役割切替',
        rol: '役割',
        menu: 'メニュー',
        categoriaTodos: 'すべて',
        buscarProducto: '製品/バーコード検索...',
        tocaParaActualizar: '製品をタップして在庫更新',
        cantidad: '数量',
        cantidadIngresar: '入庫数量',
        cantidadBaja: '出庫数量',
        guardarStock: '保存',
        actualizarStock: '在庫更新',
        stockActualizado: '在庫が更新されました',
        stockActual: '現在の在庫',
        minDef: '最低値',
        nuevoConteo: '新規棚卸',
        conteoInventario: '在庫棚卸',
        iniciarConteo: '棚卸開始',
        conteoEnProgreso: '棚卸中',
        conteoCompletado: '棚卸完了',
        escanearCodigo: 'バーコードスキャン',
        codigoBarras: 'バーコード',
        conteoFisico: '実数',
        stockSistema: 'システム在庫',
        diferencia: '差異',
        guardarConteo: '棚卸保存',
        finalizarConteo: '棚卸完了',
        productoEscaneado: '製品識別済み',
        productoNoEncontrado: 'そのコードの製品は見つかりません',
        ingresaCantidad: '棚卸数量を入力',
        escanearOtro: '次をスキャン',
        buscarManual: '手動検索',
        camaraNoDisponible: 'カメラ利用不可',
        permisosCamara: 'スキャンにはカメラアクセスを許可',
        reporteConteo: '棚卸レポート',
        sinDiferencias: '差異なし',
        conDiferencias: '差異あり',
        ajustarStock: '在庫調整',
        confirmarAjuste: '実棚に基づいて在庫を調整しますか？',
        ajusteRealizado: '調整完了',
        historialConteos: '棚卸履歴',
        noConteos: '棚卸記録なし',
        detalleConteo: '棚卸詳細',
        itemsContados: '棚卸済みアイテム',
        fecha: '日付',
        motivo: '理由',
        usuario: 'ユーザー',
        ingreso: '入庫',
        salida: '出庫',
        conteo: '棚卸',
        registros: '記録',
        categoria: 'カテゴリー',
        alerta: 'アラート',
        nivel: 'レベル',
        accion: 'アクション',
        editar: '編集',
        sinResultados: '結果なし',
        sinDatos: 'データなし',
        todas: 'すべて',
        licores: '蒸留酒',
        cervezas: 'ビール',
        vinos: 'ワイン',
        'bebidas sin alcohol': 'ソフトドリンク',
        'insumos bar': 'バー用品',
        snacks: 'スナック',
        ajustaFiltros: 'フィルターを調整してください。',
        sinProductosVencer: '期限切れ間近の製品はありません',
        tocaProductoActualizar: '製品をタップして在庫更新',
        productos: '製品',
        todosProductosVigentes: 'すべての製品の有効期限は30日以上です。',
        stockOk: '在庫OK',
        noAlertasReorden: '在庫不足アラートなし。',
        contrasenaIncorrecta: 'パスワードが間違っています。',
        seguridadAcceso: 'アクセス制御',
        ingresaContrasena: 'パスワードを入力',
        acceder: 'ログイン',
        contrasenaPlaceholder: 'パスワード / PIN',
        guardando: '保存中...',
        items: 'アイテム',
        nuevoProducto: '新規製品',
        nuevoProductoDesc: '新しい製品を登録',
        editarProducto: '製品を編集',
        editarProductoDesc: '選択した製品の情報を更新',
        eliminarProducto: '製品を削除',
        confirmarEliminar: 'この製品を削除してもよろしいですか？',
        eliminar: '削除',
        crearProducto: '製品を作成',
        guardarCambios: '変更を保存',
        cancelar: 'キャンセル',
        campoObligatorio: '製品名は必須です',
        seleccionaCategoria: 'カテゴリーを選択',
        unidad: '単位',
        proveedor: 'サプライヤー',
        descripcionProducto: '説明',
        descripcionPlaceholder: '製品の簡単な説明',
        gestionCategorias: 'カテゴリー管理',
        gestionCategoriasDesc: '製品カテゴリーの管理',
        nuevaCategoria: '新規カテゴリー',
        nombreCategoria: 'カテゴリー名',
        descripcionCategoria: '説明（任意）',
        agregarCategoria: 'カテゴリーを追加',
        sinCategorias: '登録されたカテゴリーはありません',
        cerrar: '閉じる',
        marca: 'ブランド',
        gramaje: '内容量 / 重量',
        tocaParaContar: '製品をタップして数える',
        contando: '計数中',
        tapsConteo: 'タップして数える',
        confirmarConteo: '確認',
        descartarConteo: '破棄',
        notas: 'メモ',
        notasConteo: '棚卸メモ',
        resumenDelDia: '日次サマリー — 在庫管理',
        verCatalogo: 'カタログを見る',
        escaneoRapido: '製品を識別',
        progresoConteo: '棚卸進捗',
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('es'); // Default Spanish

    // Función de traducción
    const t = useCallback((key) => {
        return translations[language][key] || key;
    }, [language]);

    const value = useMemo(() => ({
        language,
        setLanguage,
        t
    }), [language, t]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
